version: '3.8'

services:
  patient-service:
    build: ./patient-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - appointment-service

  appointment-service:
    build: ./appointment-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
